# Generated by Django 2.2.13 on 2020-06-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
